language: android
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.0
  - android-27
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- openssl aes-256-cbc -K $encrypted_4f423c7955f4_key -iv $encrypted_4f423c7955f4_iv
  -in oureda.jks.enc -out oureda.jks -d
- gem install fir-cli
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_deploy:
- mv app/build/outputs/apk/release/app-release.apk  app/build/outputs/apk/release/Youyun.apk
deploy:
  provider: releases
  api_key:
    secure: A7PriYX4XEDDxDOxxJB7QzwdJ38NlvbEHsgtZYpM5LypkP7ZpYD/K+PxyJS89nlvW7qtyvLtm5yGhYv8+xn5fUuNLI8nIoqPFmYmNhCPBkTlWWi9IMne3gCmtzifDAM1Ma3hUQ4Jd7Kauo7kRtp5PmIqdOIQ3qEzp2IR92IreUL7sTS3Dmq7WdNI1C6PK5y493D61xSLXqLvyQMq/TsDdtG9dsl1s59/B7wN7ww2+COq6a5yuJGYt4YetfOB4VNv7r8R8XGE8zb4vwbPRvRSVbOT0cTyVuGgep+cbH8ealgeSCCPgYR5T+3mfryY9XuE/gRgRPwVnRajbuLAo2n4kxpyvc2navG3qOeNw4iRoaDLNIl65RP/DKQ+UZQH30ebUS8+rKitc7lezzSHeCaQLdv+B8IYP42sW9U3Dv2GySFUlnFU9s2PgC9tvwDrATe3n17Omr6Jm85pE1k/3LVZwdrxFpDCZ4pp54kpo//VFmdhBoOENY2Vn9ULcR491xcQ/gDrvbOmHq0Tal4Y0ODYwtRhJPAtSWPWt5a/0RBpuujbQ6YiqgmQ/bLhurEjKFrWz6t971e+J51fza6PAvVbxJwKuonNcasztO//7RoacHUDV5NVsJ5rvtoaRLdOugjouoVN3Nfpvkb+PpIwGMQSGC8rXZmow3EvPNAcKujjt4w=
  file: app/build/outputs/apk/release/Youyun.apk
  skip_cleanup: true
  on:
    repo: SunnyQjm/YouyunV10
after_deploy:
- fir p app/build/outputs/apk/release/Youyun.apk -T $FIR_TOKEN -c "`git cat-file tag
  $TRAVIS_TAG`"
